#!/usr/bin/env bash
# Script to install nginx on server

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start

